baseURL: "https://ohhyemi.github.io/"
title: Hyemi's Blog
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45
disqusShortname: hyemis-blog

minify:
  disableXML: true
  minifyOutput: true

params:
  useUtterances: false
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # title: ExampleSite
  description: "Hyemi's Blog"
  keywords: [Blog, Portfolio]
  # author: Me
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  #DateFormat: "January 2, 2006"
  DateFormat: "2006년 1월 2일"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  GithubRepoUrl: "https://github.com/ohhyemi/ohhyemi.github.io"

  ShowFontSizeButton: true
  ShowCreativeCommons: true
  ShowShareButtons: true
  # ShowReadingTime: true
  #ShowPostNavLinks: true
  # ShowBreadCrumbs: true
  # ShowCodeCopyButtons: false
  # disableSpecial1stPost: false
  # disableScrollToTop: false
  #comments: true
  # hidemeta: false
  #hideSummary: false
  #showtoc: true
  #tocopen: true

  assets:
    useCustomJs: true
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/icon/favicon-64.png"
    favicon16x16: "/icon/favicon-16.png"
    favicon32x32: "/icon/favicon-32.png"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  label:
    text: ""
    icon: /icon/home.webp
    iconHeight: 25
    iconWidth: 25

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Hyemi's blog
    subtitle: "반갑습니다."
    imageUrl: "/icon/profile_pic01.webp"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Collections
        url: collection
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Write-ups ✍️
  #   ProfilePicture: "/icon/profile_pic01.webp"
    
  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: email
      url: "mailto:gpal1014@naver.com"
    - name: github
      url: "https://github.com/OhHyemi"
    # - name: instagram
    #   url: "https://instagram.com/charming_tuna"
    # - name: twitch
    #   url: "https://www.twitch.tv/charming_tuna"
    - name: link
      url: "/links"
    - name: rss
      url: "/index.xml"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  # cover:
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: false # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/OhHyemi/OhHyemi.github.io/blob/main/content"
    Text: "수정사항 제안" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
menu:
  main:
    # - identifier: series
    #   name: 시리즈
    #   url: /series-list/
    #   weight: 10
    - identifier: Posts
      name: 모두보기
      url: /posts/
      weight: 10
    - identifier: collection
      name: 모아보기
      url: /collection/
      weight: 20
    - identifier: Archive
      name: 기록 보관소
      url: /archives/
      weight: 70
    - identifier: Search
      name: 검색
      url: /search/
      weight: 80
    - identifier: Tags
      name: 태그
      url: /tags/
      weight: 90
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
taxonomies:
  series: series
  chapter: chapter
  category: categories
  tag: tags
markup:
  # goldmark:
  #   renderer:
  #     unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: true
    style: monokai
privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
